// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTohIEEpAZrFShnEqXQofP7QNHU_QRTlo',
    appId: '1:644460629560:web:cb8ff69a6d9c77dfa7a0cd',
    messagingSenderId: '644460629560',
    projectId: 'qareeb-1748d',
    authDomain: 'qareeb-1748d.firebaseapp.com',
    storageBucket: 'qareeb-1748d.firebasestorage.app',
    measurementId: 'G-1C567Y9FHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSms8_HFBp-GXl1c02e7aGKRp60opWnZQ',
    appId: '1:644460629560:android:08a0266dd4d6f888a7a0cd',
    messagingSenderId: '644460629560',
    projectId: 'qareeb-1748d',
    storageBucket: 'qareeb-1748d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBoT6b5umQgIL1WjQaY5BCw1guTZmAOtQ',
    appId: '1:644460629560:ios:d0d0420527d79696a7a0cd',
    messagingSenderId: '644460629560',
    projectId: 'qareeb-1748d',
    storageBucket: 'qareeb-1748d.firebasestorage.app',
    iosBundleId: 'com.example.qareeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBoT6b5umQgIL1WjQaY5BCw1guTZmAOtQ',
    appId: '1:644460629560:ios:d0d0420527d79696a7a0cd',
    messagingSenderId: '644460629560',
    projectId: 'qareeb-1748d',
    storageBucket: 'qareeb-1748d.firebasestorage.app',
    iosBundleId: 'com.example.qareeb',
  );
}
